export const peopleQuestions = [
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "clarify authority and reunite the team around accountable ownership.",
    text: "During construction planning, two discipline leads issue conflicting instructions because the responsibility matrix was never reviewed with the newly assembled team. What should the project manager do first?",
    choices: [
      "Review roles and decision authority with the team and update the responsibility matrix",
      "Ask the discipline leads to reconcile instructions privately and report their direction",
      "Escalate the conflicting instructions to functional managers for an authority decision",
      "Issue interim direction and defer the responsibility-matrix update to the next planning cycle",
    ],
    correct: 0,
    explanation: "The confusion comes from unclear authority, so the project manager should make ownership explicit with the assembled team. A private lead agreement may resolve one instruction but not shared understanding, functional escalation is premature, and interim project-manager direction restores speed without closing the responsibility gap that caused the conflict.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "protect team self-management while making the impediment visible.",
    text: "A product owner repeatedly assigns tasks directly to developers during the sprint, and team members have stopped volunteering work at daily coordination meetings. What should the scrum master do?",
    choices: [
      "Permit direct assignments because the product owner is accountable for product value",
      "Coach the product owner on role boundaries and help the developers restore self-management",
      "Cancel the sprint and ask the sponsor to appoint a replacement product owner",
      "Create individual utilization targets so developers accept assignments more quickly",
    ],
    correct: 1,
    explanation: "The scrum master should address the role-boundary behavior and rebuild the developers' ownership of how work is selected and performed. Product value accountability does not authorize task assignment, replacing the product owner is premature, and utilization targets would reinforce command-and-control behavior instead of team self-management.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "surface the leadership system causing silence before changing personnel or plans.",
    text: "In a regulated medical-device program, specialists meet gated approval dates but conceal integration concerns after a workstream director publicly criticizes anyone who reports uncertainty. What should the project manager do first?",
    choices: [
      "Revise milestone contingencies from current risk data and let the director address reporting behavior",
      "Introduce a confidential concern channel and review its trends at the next governance meeting",
      "Gather specific observations privately, then address psychological safety and reporting expectations with the director and team",
      "Remind specialists of reporting duties and include compliance in upcoming performance discussions",
    ],
    correct: 2,
    explanation: "The pattern indicates a leadership-created threat to truthful reporting, so the project manager needs facts and a direct reset of safe escalation expectations. Revised contingencies address exposure but delegate the behavior problem, a confidential channel delays direct repair, and reminders aimed at specialists place accountability on reporters rather than the leadership environment.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "establish a shared objective before optimizing separate functional commitments.",
    text: "Functional managers have supplied qualified engineers to an airport project, but each engineer protects departmental priorities and cross-discipline design reviews are failing. What should the project manager do next?",
    choices: [
      "Replace functional representatives with contractors who report only to the project",
      "Send unresolved design issues directly to the steering committee after each review",
      "Reward the department that closes the largest number of its own action items",
      "Facilitate a team charter session linking shared outcomes, interfaces, and decision responsibilities",
    ],
    correct: 3,
    explanation: "A chartering session creates the common purpose and interaction rules missing from this matrix team. Replacing qualified staff is disproportionate, routine escalation weakens team problem solving, and department-based rewards intensify local optimization when the project needs integrated ownership.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "use evidence and team dialogue to correct a dependency without taking work ownership away.",
    text: "A mature software team finishes stories reliably, but one senior engineer privately rewrites colleagues' code at night to prevent defects. Review quality is high, while learning and ownership are declining. What should the project leader do?",
    choices: [
      "Discuss the observed pattern with the engineer and facilitate stronger shared review and pairing practices",
      "Ask the engineer to document rewrite standards and present them at the next technical forum",
      "Make the engineer a required reviewer for high-risk components and monitor defect trends",
      "Arrange advanced coding training for colleagues identified through the rewrite history",
    ],
    correct: 0,
    explanation: "The leader should acknowledge the quality concern while changing the behavior that is eroding collective capability and ownership. Publishing standards transfers some knowledge but leaves covert rewriting intact, a required review role formalizes dependence, and targeted training assumes a capability deficit before the team has examined how review and pairing should work.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "recognize contribution in the manner the team has agreed will motivate fairly.",
    text: "After a difficult data migration, the project team meets its release objective and asks how its extra effort will be acknowledged. What should the project manager do?",
    choices: [
      "Wait until project closure because interim recognition could reduce urgency",
      "Provide timely recognition aligned with team preferences and organizational policy",
      "Recognize only the workstream leads because they accepted formal accountability",
      "Offer unapproved cash bonuses and seek finance authorization afterward",
    ],
    correct: 1,
    explanation: "Timely, appropriate recognition reinforces the desired team behavior and should respect both individual preferences and organizational rules. Delaying loses motivational value, recognizing only leaders overlooks collective effort, and promising unauthorized compensation creates an expectation the project manager may not be able to fulfill.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "diagnose system constraints before judging an apparently underperforming team.",
    text: "A rail-signaling team misses two design milestones despite working overtime. The sponsor wants the project manager to replace the team lead, but approvals arrive unpredictably from three external authorities. What should the project manager do first?",
    choices: [
      "Agree a performance improvement plan with the team lead based on the milestone variance",
      "Rebaseline upcoming design work using the observed duration of external approvals",
      "Analyze approval wait times and responsibilities with the team before deciding on a leadership change",
      "Ask the sponsor to escalate the approval delays to the relevant external authorities",
    ],
    correct: 2,
    explanation: "The available evidence points to an external workflow constraint, so the project manager should separate system delay from leadership performance before acting. A performance plan assumes the lead caused the variance, rebaselining incorporates delay without clarifying responsibility, and sponsor escalation selects a response before the team has measured where approvals actually wait.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "let the team own an improvement experiment and its evidence.",
    text: "Retrospectives identify the same slow test-environment setup every sprint, but the team expects the agile coach to prescribe a solution. What should the coach do?",
    choices: [
      "Select a commercial automation tool and require the team to adopt it immediately",
      "Escalate the repeated issue because a retrospective should solve every impediment",
      "Remove environment setup from the definition of done for the next release",
      "Help the team choose a small improvement experiment, owner, and measure for the next sprint",
    ],
    correct: 3,
    explanation: "A bounded experiment builds self-management and produces evidence about whether the improvement works. Prescribing a tool bypasses team analysis, escalation is not yet necessary, and weakening the definition of done disguises the setup problem instead of improving the team's way of working.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "adapt leadership to team maturity while preserving governance boundaries.",
    text: "An experienced analytics squad joins a bank transformation and requests authority to select its iteration practices, while the program requires fixed monthly risk evidence. How should the project manager lead the squad?",
    choices: [
      "Delegate working-method decisions to the squad while defining the required risk evidence and review boundaries",
      "Require the squad to use the program office's detailed task plan because governance is fixed",
      "Let the squad decide whether monthly risk evidence is useful after its first release",
      "Ask the program sponsor to approve each iteration practice selected by the squad",
    ],
    correct: 0,
    explanation: "The mature squad can own its working methods while still satisfying nonnegotiable governance outputs. A detailed imposed plan wastes its capability, optional risk evidence violates the program constraint, and sponsor approval of routine team practices creates unnecessary decision delay.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Team leadership",
    domain: "People",
    topic: "Team leadership",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "model the behavior expected from the team and correct contrary signals promptly.",
    text: "A project manager asks a public-infrastructure team to report safety concerns immediately, then routinely postpones meetings where those concerns are discussed. What is the most effective corrective action?",
    choices: [
      "Ask the safety officer to consolidate concerns for the next scheduled risk review",
      "Prioritize timely safety reviews and explain the changed behavior to the team",
      "Add a standing safety agenda item without closing concerns from the postponed meetings",
      "Reissue the reporting-channel guidance and monitor the volume of new submissions",
    ],
    correct: 1,
    explanation: "Leadership credibility depends on matching actions to stated priorities, so the project manager must review the existing concerns promptly and make the changed behavior visible. Consolidating them for a later risk review delays response and transfers ownership, a standing agenda item lacks closure on the backlog, and reissuing channel guidance measures reporting rather than demonstrating that reported concerns receive action.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "make the substantive disagreement discussable before choosing a resolution.",
    text: "A UX designer and an accessibility specialist argue repeatedly during backlog refinement, while other team members have begun avoiding items that require both perspectives. What should the project manager do first?",
    choices: [
      "Assign the disputed items to whichever specialist has more organizational seniority",
      "Separate the specialists and ask them to document competing designs independently",
      "Facilitate a focused conversation to identify interests, evidence, and shared acceptance criteria",
      "Defer all disputed items until the rest of the product backlog is completed",
    ],
    correct: 2,
    explanation: "A facilitated discussion exposes the needs beneath their positions and gives the team objective criteria for resolving the product tradeoff. Seniority is not evidence, separate designs may entrench positions, and indefinite deferral allows interpersonal avoidance to dictate product priority.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "resolve role conflict at the lowest effective level without compromising safety.",
    text: "During a factory retrofit, an agile controls team wants to test increments on operating equipment, but the predictive commissioning lead refuses any access before formal readiness approval. Both cite legitimate obligations. What should the project manager do?",
    choices: [
      "Authorize an offline replica test and defer operating-equipment access until formal readiness",
      "Follow the current readiness gate and place earlier test access on the next governance agenda",
      "Prepare the feedback and safety impacts for the sponsor to select the governing approach",
      "Bring both leads together to define a safe test boundary and an approval path that serves both needs",
    ],
    correct: 3,
    explanation: "The competing positions reflect valid feedback and safety interests, so collaborative problem solving should create controlled access and explicit approvals. Replica testing provides feedback but may not test the operating interface, waiting for the next governance cycle protects safety but loses near-term learning, and sponsor selection escalates before the leads attempt an integrated boundary.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "address a stakeholder conflict through direct, interest-based engagement first.",
    text: "A municipal project faces opposition from a neighborhood representative who demands nighttime work stop, while the contractor says daytime restrictions will delay the opening. What should the project manager do first?",
    choices: [
      "Meet with both parties to explore underlying constraints and feasible schedule alternatives",
      "Enforce the contractor's approved schedule because it forms part of the contract",
      "Ask the mayor to overrule the neighborhood representative before further discussion",
      "Suspend all work until every affected resident provides written consent",
    ],
    correct: 0,
    explanation: "Direct interest-based discussion can reveal options such as sequencing, noise controls, or limited work windows while preserving relationships. Simply enforcing the schedule ignores community impact, political escalation is premature, and requiring unanimous resident consent creates an impractical condition not established in the scenario.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "do not confuse temporary harmony with resolution of a recurring value conflict.",
    text: "Two product managers repeatedly trade features between releases to avoid open disagreement, but their unresolved market priorities cause engineers to rework architecture each quarter. What should the product portfolio manager do next?",
    choices: [
      "Formalize the feature trades in the release plan and track the resulting rework risk",
      "Facilitate a decision using agreed product goals, market evidence, and explicit priority authority",
      "Fund an architecture buffer for the most likely priority changes in later releases",
      "Ask the product sponsor to select the next release priority from the existing business case",
    ],
    correct: 1,
    explanation: "The feature trades postpone the underlying priority conflict, so the portfolio manager should anchor a durable decision in shared goals, current evidence, and clear authority. Formalizing trades makes risk visible without resolving it, an architecture buffer mitigates rework rather than priorities, and a sponsor choice from the old business case omits the shared criteria and current market evidence needed for sustained alignment.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "use an agreed escalation path when direct collaboration has reached impasse.",
    text: "A nonprofit program's legal lead and delivery lead have met twice but remain deadlocked over releasing a donor portal with an unresolved consent clause. The issue now threatens a public commitment. What should the project manager do?",
    choices: [
      "Release the portal because the delivery lead owns the committed date",
      "Remove the consent feature without informing the donor steering group",
      "Escalate the documented options and impacts through the agreed governance path",
      "Ask the two leads to keep meeting without a decision deadline",
    ],
    correct: 2,
    explanation: "Direct resolution has been attempted and the issue exceeds the team's authority, so a timely governance decision using documented impacts is appropriate. Shipping despite legal concern is reckless, silently changing scope violates transparency, and indefinite discussion leaves the external commitment unmanaged.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "separate factual disagreement from personal attribution before deciding corrective action.",
    text: "After a laboratory validation fails, the quality manager blames technician discipline while the engineering manager claims the test protocol is ambiguous. Their teams stop sharing records. What should the project manager do first?",
    choices: [
      "Ask quality to refresh technician training while engineering reviews the protocol separately",
      "Commission an independent specialist to revise the protocol before restoring record sharing",
      "Escalate the failed validation and request separate corrective-action plans from both managers",
      "Convene a fact-based review of the protocol, execution records, and handoffs with both managers",
    ],
    correct: 3,
    explanation: "A joint evidence review distinguishes process ambiguity from execution variance and reopens information flow before blame hardens. Parallel training and protocol review preserve the competing assumptions, independent revision changes the artifact before establishing the cause, and separate corrective plans formalize positions without the shared evidence needed to integrate a response.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "reinforce team working agreements when debate becomes disrespectful.",
    text: "During sprint planning, a developer interrupts a tester and dismisses the tester's estimates as uninformed. The team charter requires respectful challenge. What should the scrum master do?",
    choices: [
      "Pause the exchange, restate the working agreement, and invite the tester to explain the estimate",
      "Ignore the interruption because robust technical debate improves agile decisions",
      "End planning and send the developer directly to human resources",
      "Accept the developer's estimate because coding experience is more relevant",
    ],
    correct: 0,
    explanation: "Immediate, proportionate intervention protects participation and uses the team's own agreement to redirect the conversation. Ignoring disrespect damages safety, an immediate human-resources referral is excessive for the stated event, and privileging the developer's estimate repeats the dismissal instead of examining evidence.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "resolve scarce-resource conflict against transparent project priorities and authority.",
    text: "Two workstream leads need the same cybersecurity architect this week. One task protects a fixed regulatory gate; the other validates a high-value product hypothesis. Informal negotiation has failed. What should the project manager do next?",
    choices: [
      "Split the architect's time equally so both leads perceive the outcome as fair",
      "Apply documented priorities and decision authority, then communicate the tradeoff and impacts",
      "Give the architect the choice so the project manager remains neutral",
      "Add both tasks to the architect's workload and recover any delay through overtime",
    ],
    correct: 1,
    explanation: "When informal negotiation fails, transparent criteria and established authority should determine the allocation while impacts are made visible. Equal time may satisfy neither need, delegating the conflict to the architect avoids accountability, and overloading a scarce specialist creates quality and sustainability risks.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Conflict management",
    domain: "People",
    topic: "Conflict management",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "select collaboration when the relationship and technical outcome both matter.",
    text: "A museum renovation architect and curator disagree about protecting a historic wall while routing new climate controls. Both outcomes are essential. Which conflict approach should the project manager encourage?",
    choices: [
      "Withdraw from the issue until one specialist changes position voluntarily",
      "Force the architect's solution because construction responsibility carries more authority",
      "Collaborate to develop an option that satisfies preservation and environmental requirements",
      "Compromise by meeting only half of each documented requirement",
    ],
    correct: 2,
    explanation: "Collaboration is appropriate because the relationship and both mandatory outcomes matter, and an integrative design may satisfy them together. Withdrawal delays a necessary decision, forcing ignores curatorial needs, and splitting requirements treats compliance and preservation as negotiable without evidence that either can be reduced.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "interpret a team metric through delivery evidence before treating it as a target.",
    text: "A sponsor notices that an agile team's velocity declined after it began pairing on complex security stories, although escaped defects also declined. The sponsor asks for individual productivity targets. What should the project manager do?",
    choices: [
      "Set story-point quotas for each developer to restore the prior velocity",
      "Stop pairing until the team reaches its earlier output level",
      "Exclude security stories from velocity because their estimates are unusually uncertain",
      "Review value, quality, and flow trends with the sponsor and team before changing the practice",
    ],
    correct: 3,
    explanation: "Velocity alone cannot show whether performance worsened, especially when quality improved on complex work. Individual quotas misuse a team estimate, stopping pairing discards a possible cause of fewer defects, and excluding difficult work manipulates the metric rather than explaining delivery outcomes.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "treat sustained overtime as a system signal and restore a sustainable operating model.",
    text: "A global payments team has met three release dates through repeated weekend work. Defects, sick leave, and handoff delays are now increasing, but the next contractual milestone is near. What should the project manager do first?",
    choices: [
      "Analyze workload and flow with the team, then agree immediate scope or capacity adjustments",
      "Secure temporary capacity for the milestone and review sustainable workload after the release",
      "Request that the sponsor remove low-value scope based on the current defect trend",
      "Strengthen defect triage and sick-leave coverage for the remaining milestone work",
    ],
    correct: 0,
    explanation: "Rising defects, absence, and delays show that overtime is no longer protecting performance, so workload and capacity need immediate analysis with the team before an adjustment is selected. Temporary staff defer sustainability, sponsor scope reduction is chosen without team flow analysis, and stronger triage and coverage manage symptoms while leaving excess demand intact.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "close a verified capability gap before attributing variance to motivation.",
    text: "A newly hired estimator produces inconsistent quantities on a highway project. The approved estimating method differs from the tool used at the estimator's previous employer. What should the project manager do next?",
    choices: [
      "Reduce the estimator's performance rating before the next quantity submission",
      "Arrange targeted training and supervised practice on the approved method",
      "Transfer all estimating work permanently to the senior engineer",
      "Change the project's estimating method to match the new employee's prior tool",
    ],
    correct: 1,
    explanation: "The scenario identifies a specific knowledge gap, making targeted development and observed practice the proportionate response. A negative rating assumes unwillingness, permanent transfer prevents capability growth and overloads the senior engineer, and changing the project method for one person's familiarity may violate approved controls.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "improve the conditions behind uneven participation instead of optimizing visible activity.",
    text: "A remote product team completes sprint goals, but retrospective data show that two developers handle nearly all production incidents and cannot finish planned learning work. What should the team leader do?",
    choices: [
      "Reserve the next sprint's learning allocation as contingency for production incidents",
      "Create a dedicated responder rotation led by the two experts and review it next release",
      "Facilitate skills sharing and redesign the support rotation with the whole team",
      "Adjust capacity forecasts for incident duty and protect other members' sprint commitments",
    ],
    correct: 2,
    explanation: "Cross-training and a redesigned rotation address the concentration of operational knowledge while preserving sustainable delivery. Converting learning time to contingency deepens the gap, a rotation still led by the same experts retains dependence, and capacity forecasting describes the load but does not distribute incident skill or ownership.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "use team-owned measures that connect working behavior to outcomes.",
    text: "A consumer-goods launch team wants to know whether its new daily cross-functional huddle is reducing late packaging decisions. What should the project manager recommend?",
    choices: [
      "Agree on a short trial and track decision lead time and late packaging changes",
      "Count meeting attendance because full participation proves the huddle is effective",
      "Continue the huddle for the full project before collecting any performance data",
      "Measure each participant's speaking time to ensure equal individual contribution",
    ],
    correct: 0,
    explanation: "A time-boxed trial with outcome-related measures can show whether the huddle improves the targeted decision flow. Attendance is an activity measure, delayed evaluation prevents adaptation, and equal speaking time does not demonstrate faster decisions or fewer packaging changes.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "revise team development actions when performance evidence disproves the original diagnosis.",
    text: "A project manager arranged presentation training after client workshops received poor ratings. Ratings remain low, while recordings show experts answer accurately but avoid confirming whether client concerns were understood. What should happen next?",
    choices: [
      "Ask the training provider to add client-specific presentation exercises to the course",
      "Reassess the gap and coach active listening and confirmation techniques using the recordings",
      "Pair the experts with client relationship managers to lead the next workshops",
      "Collect written client questions before each workshop and revise the presentation agenda",
    ],
    correct: 1,
    explanation: "New evidence shows the issue is listening and confirmation rather than presentation mechanics, so the development response must change. More tailored presentation exercises still target the wrong skill, relationship managers may compensate without developing the experts, and advance written questions improve preparation but do not establish whether concerns were understood during discussion.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "make impediments visible and let the team inspect its delivery system.",
    text: "A mobile-app team carries the same three blocked stories across successive sprints, yet its review meetings focus only on completed demonstrations. What should the scrum master do?",
    choices: [
      "Increase the blocked stories' estimates so the velocity reflects their difficulty",
      "Remove the stories from the product backlog until external dependencies disappear",
      "Facilitate inspection of the blockers, aging work, and ownership of next actions",
      "Ask developers to work on the blocked stories outside normal sprint hours",
    ],
    correct: 2,
    explanation: "The team needs transparent inspection of why work remains blocked and who will act on dependencies. Re-estimating does not unblock anything, removing needed work hides demand, and off-hours effort cannot solve external constraints and encourages an unsustainable workaround.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "align performance feedback with the outcomes and behaviors the integrated team controls.",
    text: "In a hospital rollout, functional managers assess staff only on departmental output, while the project depends on collaborative ward readiness. Team members therefore defer integration work. What should the project manager do?",
    choices: [
      "Create a separate ranking and publish which individuals complete the most integration tasks",
      "Accept the functional measures because only line managers can evaluate employees",
      "Escalate every deferred task to the hospital director for individual resolution",
      "Work with functional managers to include agreed project collaboration and readiness outcomes in feedback",
    ],
    correct: 3,
    explanation: "Coordinating evaluation criteria with functional managers aligns incentives to the integrated results the project needs. A competing public ranking harms cooperation, accepting the mismatch leaves the cause intact, and repeated executive escalation manages symptoms one task at a time.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Team performance",
    domain: "People",
    topic: "Team performance",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "assess team effectiveness against agreed objectives using multiple relevant indicators.",
    text: "A project board asks whether a procurement-transition team is performing effectively. The team meets dates, but suppliers report frequent clarification loops and employees report avoidable rework. What should the project manager provide?",
    choices: [
      "An assessment combining milestone, rework, supplier-feedback, and team-development evidence",
      "Only the schedule report because approved milestones define project performance",
      "A list of the individuals involved in the largest number of clarification loops",
      "A statement that the team is effective because no formal complaint has been filed",
    ],
    correct: 0,
    explanation: "A balanced assessment tests effectiveness against delivery, quality, stakeholder, and team evidence rather than one favorable indicator. Schedule alone hides rework, naming individuals skips causal analysis, and absence of formal complaints does not invalidate the feedback already described.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "regulate the immediate reaction and seek meaning before responding to criticism.",
    text: "At a sprint review, a major customer says the increment shows that the team does not understand its business. The product lead becomes visibly defensive. What should the project manager do first?",
    choices: [
      "Acknowledge the concern, ask for concrete examples, and keep the discussion focused on learning",
      "Defend the team by listing every requirement the customer previously approved",
      "End the review and request that future feedback be submitted only in writing",
      "Promise to replace the product lead before confirming the source of dissatisfaction",
    ],
    correct: 0,
    explanation: "Acknowledging emotion without accepting a vague conclusion creates space for specific evidence and learning. A defensive requirements recital escalates the exchange, ending live feedback reduces collaboration, and promising a personnel change before understanding the concern is impulsive and unsupported.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "read behavioral changes as data and inquire privately without diagnosing the person.",
    text: "A previously outspoken clinical lead becomes silent after a contentious governance meeting, approves every decision quickly, and stops raising patient-safety tradeoffs. No complaint has been made. What should the project manager do?",
    choices: [
      "Ask the lead in writing to document patient-safety objections before the next gate",
      "Meet privately, describe the observed change, and invite the lead's perspective and concerns",
      "Ask the governance chair whether recent meeting dynamics explain the reduced participation",
      "Add an independent safety reviewer to upcoming approvals while monitoring participation",
    ],
    correct: 1,
    explanation: "A private, observation-based inquiry demonstrates empathy and may uncover safety or relationship concerns without making an unsupported attribution. A written request asks for output without exploring the change, asking the chair investigates through a third party first, and adding a reviewer protects coverage but bypasses the lead whose withdrawal needs to be understood.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "recognize personal triggers before choosing a proportionate response.",
    text: "A sponsor questions the project manager's forecast in front of the steering committee. The forecast is supported, but the project manager feels an urge to challenge the sponsor's own missed decisions. What should the project manager do?",
    choices: [
      "Challenge the sponsor immediately so the committee sees that accountability is mutual",
      "Withdraw the forecast until the sponsor provides a private apology",
      "Pause, explain the forecast assumptions calmly, and arrange follow-up on decision delays separately",
      "Ask the team to answer all further forecast questions to avoid personal conflict",
    ],
    correct: 2,
    explanation: "Self-awareness and regulation allow the project manager to defend the evidence without retaliating, while preserving a later conversation about sponsor actions. Public counterattack shifts focus, withdrawing sound data is coercive, and transferring all questions to the team avoids rather than manages the leadership relationship.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "combine empathy with accountability when distress affects team commitments.",
    text: "A developer who recently experienced a family emergency misses stand-ups and leaves paired work unfinished. Teammates are sympathetic but are quietly absorbing the work and becoming frustrated. How should the team leader respond?",
    choices: [
      "Quietly reduce the developer's allocation and ask the pairing partner to cover unfinished work",
      "Ask human resources about leave options before discussing capacity with the developer",
      "Reassign the paired work for this sprint and revisit support when the emergency stabilizes",
      "Speak privately about capacity and support, then transparently rebalance commitments with the team",
    ],
    correct: 3,
    explanation: "A private capacity conversation respects the person's circumstances while allowing commitments and workload to be adjusted openly. Quiet allocation changes conceal impacts from both parties, consulting human resources first assumes a remedy before hearing the developer, and unilateral sprint reassignment handles work temporarily without establishing support or a transparent team commitment.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "adapt communication to the listener's emotional state without concealing facts.",
    text: "A department manager learns that automation will change several employees' duties and begins asking rapid, repetitive questions during a readiness workshop. What should the project manager do?",
    choices: [
      "Acknowledge the concern, slow the discussion, and clarify impacts and available transition support",
      "Continue the prepared slides because changing pace would reward disruptive behavior",
      "Assure the manager that no employee will be affected, even though role design is incomplete",
      "Ask security to remove the manager so the remaining attendees can finish the workshop",
    ],
    correct: 0,
    explanation: "Recognizing anxiety and adapting the conversation helps the manager process accurate information and engage constructively. Rigidly continuing ignores the audience, unsupported reassurance damages trust, and removal escalates a concerned stakeholder's behavior without first attempting a respectful response.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "test an attribution against evidence before letting it drive a people decision.",
    text: "A project manager believes a quiet engineer is resisting the project because the engineer rarely speaks in executive meetings. Written risk analyses from the engineer are detailed and timely. What should the project manager do?",
    choices: [
      "Add verbal participation as a development objective for the next performance checkpoint",
      "Check the assumption with the engineer and agree on effective ways to contribute in the meeting context",
      "Invite the engineer to present the next risk summary with coaching support",
      "Route the written analyses through an experienced executive communicator",
    ],
    correct: 1,
    explanation: "The written work contradicts the assumption of resistance, so the project manager should examine personal attribution and discuss contribution preferences and meeting needs. A verbal-development objective assumes a deficiency, a coached presentation selects a remedy before understanding the engineer's view, and routing analysis through another communicator sidelines useful expertise rather than agreeing an effective contribution method.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "notice exclusion signals and create room for the affected person to participate.",
    text: "During an energetic design workshop, three senior members talk over a junior data analyst who has twice tried to mention a privacy constraint. What should the facilitator do?",
    choices: [
      "Let the discussion continue because senior members are accountable for the design",
      "Ask the analyst to email the concern after the workshop to preserve momentum",
      "Pause the discussion and invite the analyst to explain the privacy constraint",
      "End the workshop and report all three senior members for formal discipline",
    ],
    correct: 2,
    explanation: "The facilitator should respond to the visible exclusion and bring potentially critical information into the decision now. Continuing privileges hierarchy, deferring to email separates the analyst from the live reasoning, and formal discipline is disproportionate before a direct facilitation intervention.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Emotional intelligence",
    domain: "People",
    topic: "Emotional intelligence",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "repair trust by naming impact and listening, not by defending intent.",
    text: "A project manager jokes about an operations team's slow approvals during a joint demo. Operations representatives become reserved and stop offering implementation advice. What should the project manager do next?",
    choices: [
      "Explain that the comment was humorous and ask everyone to be less sensitive",
      "Ignore the reaction because operations still attends required meetings",
      "Ask the sponsor to reassure operations that the project manager meant no harm",
      "Acknowledge the comment's impact, apologize directly, and invite operations' concerns",
    ],
    correct: 3,
    explanation: "A direct acknowledgment and genuine listening address the relationship damage regardless of the project manager's intent. Defending the joke dismisses impact, mere attendance does not indicate engagement, and using the sponsor as an intermediary avoids personal accountability for repairing trust.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "identify influence, interest, and expectations before choosing engagement actions.",
    text: "A new environmental agency is created midway through a coastal engineering project and may influence upcoming permits. The agency is not in the stakeholder register. What should the project manager do first?",
    choices: [
      "Analyze the agency's authority and expectations, then update stakeholder information and engagement plans",
      "Wait until the agency contacts the project because its exact interest is still unknown",
      "Send the full technical archive without first identifying what information the agency needs",
      "Ask the sponsor to exclude the agency because project planning is already complete",
    ],
    correct: 0,
    explanation: "A newly relevant stakeholder should be identified and analyzed before tailored engagement begins. Waiting risks permit surprises, sending an undifferentiated archive is not purposeful engagement, and a sponsor cannot simply remove a legally influential agency from the stakeholder environment.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "remove practical barriers to frequent feedback from the real decision maker.",
    text: "A retail product owner delegates each sprint review to an analyst who can explain results but cannot change priorities, release timing, or stakeholder tradeoffs. Feedback waits several days for decisions, causing rework. What should the scrum master do?",
    choices: [
      "Ask the analyst to record feedback and defer product decisions to backlog refinement",
      "Work with the product owner to adjust review timing and clarify delegable product decisions",
      "Collect prioritized stakeholder feedback before the review for the analyst to apply",
      "Use the definition of done to decide which review feedback enters the next sprint",
    ],
    correct: 1,
    explanation: "A sprint review is collaborative inspection and adaptation, not a product-owner acceptance gate, but timely product decisions still require accountable authority. Recording feedback until refinement preserves delay, a prepared priority list cannot cover emerging tradeoffs, and the definition of done establishes increment quality rather than product priority, release timing, or stakeholder choices.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "engage legitimate local voices early enough to shape both delivery and relationship outcomes.",
    text: "A renewable-energy program has national approval, but an Indigenous council says route planning ignored seasonal access to culturally significant land. Survey work is scheduled to begin next week. What should the program manager do first?",
    choices: [
      "Proceed with surveys outside mapped cultural areas while legal confirms consultation status",
      "Ask public affairs to brief the council on approved mitigation and record objections",
      "Pause affected survey activity and engage council representatives on impacts, protocols, and alternatives",
      "Have the field vendor draft an alternate access route for council review before surveying",
    ],
    correct: 2,
    explanation: "The council has raised a material impact and consultation gap, so affected work should pause while authorized representatives shape a respectful path forward. Proceeding outside mapped areas assumes the disputed boundary is reliable, a mitigation briefing invites reaction rather than participation, and a vendor route proposal selects a technical response before agreeing impacts and cultural protocols.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "tailor engagement when observed stakeholder behavior differs from the desired state.",
    text: "A finance director categorized as supportive has skipped three design approvals and now questions assumptions already documented in workshops. The delay is affecting the baseline. What should the project manager do?",
    choices: [
      "Reclassify the director as resistant and increase the frequency of written decision reminders",
      "Ask the deputy finance controller to issue provisional approvals within delegated limits",
      "Escalate the missed approvals and schedule impact with the prior workshop record",
      "Meet with the director to understand the change, then update engagement actions and approval arrangements",
    ],
    correct: 3,
    explanation: "Engagement assessment must reflect actual behavior, and direct inquiry may reveal workload, unresolved concerns, or an ineffective approval format. Reclassification and reminders interpret the behavior before understanding it, provisional delegation addresses timing but not reopened assumptions, and escalation is premature before a direct conversation tests the cause and workable approval arrangement.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "convert conflicting stakeholder preferences into transparent product choices and feedback loops.",
    text: "For an education platform, teachers prioritize accessibility, district buyers prioritize reporting, and students prioritize mobile speed. Each group claims to represent the customer, and backlog decisions are stalling. What should the product leader do?",
    choices: [
      "Facilitate shared outcome criteria, clarify product decision authority, and test assumptions with each group",
      "Allocate initial capacity evenly among the groups and compare adoption after release",
      "Ask the product owner to rank requests using the current revenue model",
      "Prioritize district reporting first and schedule teacher and student discovery afterward",
    ],
    correct: 0,
    explanation: "Shared outcomes, explicit authority, and direct validation make competing needs visible and support coherent product decisions. Equal capacity postpones the value judgment until after release, the revenue model narrows evidence to the purchaser, and reporting-first sequencing delays accessibility and user-performance learning that may change the product direction.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "involve operational stakeholders before a handover decision becomes irreversible.",
    text: "A logistics system is technically ready for deployment, but warehouse supervisors have not reviewed the new exception workflow they will operate. What should the project manager do next?",
    choices: [
      "Deploy on schedule because technical acceptance proves operational readiness",
      "Arrange a hands-on workflow review and capture supervisor feedback before deployment approval",
      "Send supervisors the user manual after deployment so they learn from actual use",
      "Ask the sponsor to accept operational risk without informing the supervisors",
    ],
    correct: 1,
    explanation: "The supervisors' operational knowledge and adoption are needed before approving deployment, so a focused hands-on review is appropriate. Technical acceptance alone is insufficient, post-deployment manuals delay engagement, and sponsor risk acceptance without the affected operators' input hides a preventable readiness gap.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "preserve governance independence while engaging an influential sponsor constructively.",
    text: "An executive sponsor asks the project manager to exclude an internal auditor from early discussions because the auditor may slow a confidential acquisition-integration project. Audit review is mandatory before the next gate. What should the project manager do?",
    choices: [
      "Delay auditor contact until gate preparation, then provide the complete evidence package",
      "Engage the audit liaison under confidentiality terms and brief the sponsor after defining scope",
      "Explain the governance need and agree with both parties on secure, timely auditor involvement",
      "Ask legal counsel to define minimum disclosure before scheduling auditor participation",
    ],
    correct: 2,
    explanation: "Mandatory independent review must be protected, while confidentiality can be handled through secure and proportionate engagement agreed with both key parties. Waiting until gate preparation creates late rework risk, defining audit scope before sponsor alignment preserves review but sequences transparency poorly, and a legal disclosure opinion may help later but defers the immediate engagement design unnecessarily.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "show stakeholders how their feedback changed the product to sustain participation.",
    text: "Call-center agents contributed many ideas during discovery but stopped attending demos because they never hear what happened to their suggestions. What should the project manager do?",
    choices: [
      "Require attendance because agents were formally designated as key stakeholders",
      "Replace agents with their manager so only one person needs progress information",
      "Collect more suggestions through an anonymous survey before each demo",
      "Close the feedback loop by showing decisions, rationale, and upcoming opportunities to test changes",
    ],
    correct: 3,
    explanation: "Visible disposition of feedback demonstrates that participation matters even when every suggestion is not adopted. Compulsory attendance does not create engagement, replacing users weakens direct insight, and collecting still more input without explaining prior decisions repeats the reason agents disengaged.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "plan engagement around a stakeholder's real decision cadence and information needs.",
    text: "A university provost supports a campus transformation but reviews decisions only at quarterly councils, while delivery teams need guidance every two weeks. What should the project manager do?",
    choices: [
      "Agree on delegated decision thresholds and concise interim briefings that fit the provost's governance cadence",
      "Send daily technical status reports so the provost has enough detail to respond faster",
      "Let teams make every strategic decision until the next quarterly council",
      "Delay all work requiring guidance because formal councils are the only valid engagement channel",
    ],
    correct: 0,
    explanation: "Delegated thresholds and tailored briefings connect delivery speed to the provost's legitimate governance rhythm. Daily technical detail is unlikely to solve access, unrestricted team decisions exceed authority, and delaying every decision sacrifices progress when a clear delegation model can provide control.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Stakeholder engagement",
    domain: "People",
    topic: "Stakeholder engagement",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "verify stakeholder satisfaction directly rather than infer it from contract compliance.",
    text: "A consulting project has delivered every contractual report on time, yet client representatives rarely comment and decline optional review sessions. How should the project manager assess engagement?",
    choices: [
      "Assume engagement is sufficient because all contractual deliverables were accepted",
      "Ask client representatives about usefulness, concerns, and preferred review methods",
      "Increase report length so silence cannot be attributed to missing detail",
      "Record the client as resistant because optional sessions were declined",
    ],
    correct: 1,
    explanation: "Direct inquiry tests whether accepted outputs are useful and whether the current review method fits stakeholder needs. Contract acceptance alone does not prove active engagement, longer reports may worsen access, and labeling resistance without understanding the behavior is an unsupported attribution.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "choose a richer communication channel when ambiguity requires immediate exchange.",
    text: "A distributed team debates a complex architecture decision through a long messaging thread. Responses cross, assumptions multiply, and no one can state the current proposal. What should the team leader do?",
    choices: [
      "Ask everyone to stop responding until the architect publishes a final decision",
      "Move the thread to a shared archive and allow another day for written comments",
      "Convene an interactive visual session, resolve assumptions, and record the resulting decision",
      "Forward the entire thread to the sponsor and request a technical ruling",
    ],
    correct: 2,
    explanation: "A high-ambiguity technical issue needs synchronous, visual, two-way communication followed by a durable record. Unilateral architect closure bypasses perspectives, more asynchronous comments sustain confusion, and sponsor escalation transfers a technical collaboration problem to someone unlikely to hold the required detail.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "balance speed, accuracy, and authorization during sensitive incident communication.",
    text: "A data breach may affect customers during a staged platform release. Facts are incomplete, social media speculation is growing, and only the incident spokesperson may make public statements. What should the project manager do first?",
    choices: [
      "Draft a holding statement from the engineering assessment for spokesperson approval",
      "Complete a rapid impact assessment before external communication while briefing governance",
      "Ask customer support to use the existing breach FAQ with potentially affected accounts",
      "Activate the incident communication path, provide verified facts to the spokesperson, and set update times",
    ],
    correct: 3,
    explanation: "The approved incident path enables timely, consistent communication while distinguishing verified facts from unknowns and promising updates. A holding statement alone omits the wider response cadence, completing impact analysis before activation delays the authorized path, and an existing FAQ may not match verified breach facts or the spokesperson-only communication constraint.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "tailor content and format to the receiver's decisions rather than the sender's available detail.",
    text: "The steering committee complains that a forty-page weekly engineering report does not reveal which decisions threaten the refinery turnaround date. What should the project manager do?",
    choices: [
      "Redesign the report around required decisions, impacts, owners, and concise supporting indicators",
      "Add all raw engineering logs so committee members can perform their own analysis",
      "Continue the approved format because changing it could create inconsistent historical records",
      "Stop written reporting and rely on informal conversations with individual committee members",
    ],
    correct: 0,
    explanation: "The communication should enable the committee's governance decisions, with detail available as support rather than obscuring action. More raw data increases overload, format history is not a reason to preserve ineffectiveness, and informal individual conversations remove a consistent shared record.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "verify shared meaning when the same term drives different delivery expectations.",
    text: "A product owner says a feature is ready for pilot, while operations understands ready to mean fully supportable at scale. Both used the same dashboard status and now blame each other. What should the project manager do first?",
    choices: [
      "Use the product owner's pilot definition now and treat scale readiness as a later gate",
      "Facilitate agreement on explicit readiness criteria and update the shared information radiator",
      "Add separate pilot and scale-readiness fields to the dashboard before agreeing ownership",
      "Ask the sponsor to approve an enterprise readiness definition for the governance glossary",
    ],
    correct: 1,
    explanation: "The conflict arises from unverified meaning, so explicit shared criteria and a corrected visible status prevent recurrence. Applying the product definition unilaterally defers operational alignment, adding dashboard fields improves labels without agreeing criteria or ownership, and a sponsor-defined glossary is slower and less collaborative than resolving the concrete pilot decision with those doing the work.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "protect confidential information while ensuring authorized recipients can act.",
    text: "A merger project includes confidential staffing decisions. Workstream leads need dependency dates but are not authorized to see employee names. How should the project manager communicate?",
    choices: [
      "Share the full staffing file because dependency management requires complete transparency",
      "Withhold all schedule information until the merger is publicly announced",
      "Provide authorized, need-to-know timing and role information without personal details",
      "Let each workstream lead ask employees directly whether their roles will change",
    ],
    correct: 2,
    explanation: "Need-to-know communication can provide actionable dependency information while preserving confidentiality and access controls. Full disclosure exceeds authorization, total withholding prevents planning, and direct questioning invites rumors and places employees in a sensitive process they may not be permitted to discuss.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Predictive",
    difficulty: "Hard",
    decisionRule: "treat repeated message failure as a communication-system problem requiring feedback.",
    text: "Safety bulletins are translated and emailed to all shipyard crews, yet inspections show repeated misunderstanding among temporary workers. Delivery receipts confirm that the messages arrived. What should the project manager do next?",
    choices: [
      "Improve specialist terminology in the translation and resend it with acknowledgment tracking",
      "Ask supervisors to conduct toolbox talks and submit signed completion records",
      "Assign bilingual safety champions to temporary crews for the next work phase",
      "Use demonstrations and teach-back with the crews, then confirm comprehension through observation",
    ],
    correct: 3,
    explanation: "Receipt is not comprehension, so demonstration, teach-back, and observation provide direct feedback about whether critical behavior was understood. Better translation still relies on acknowledgment rather than meaning, signed toolbox talks confirm attendance but not comprehension, and bilingual champions provide support without verifying that each worker can apply the instruction.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Agile",
    difficulty: "Easy",
    decisionRule: "make frequently changing work status visible at the point of collaboration.",
    text: "Marketing repeatedly asks developers which experiment is live because the release status spreadsheet is updated only at the end of each week. What should the project manager recommend?",
    choices: [
      "Create a shared, current visual board showing experiment state, owner, and next decision",
      "Ask marketing to wait for the weekly spreadsheet to avoid interrupting developers",
      "Have each developer send separate daily emails describing individual activity",
      "Give marketing access to source-code commits and let them infer release status",
    ],
    correct: 0,
    explanation: "A current shared visual source answers the recurring coordination need without repeated interruption and can show business-relevant state. Waiting preserves stale information, individual emails fragment the picture, and raw code activity does not reliably communicate whether an experiment is live or awaiting a decision.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "address damaging rumors with timely facts and a credible path for unknowns.",
    text: "Employees hear that a new scheduling system will eliminate flexible shifts, although policy decisions are still open. Rumors are reducing participation in user testing. What should the change project manager do?",
    choices: [
      "Remain silent until every policy is final so no message needs correction",
      "State what is decided and undecided, explain the decision process, and invite questions",
      "Deny that any shift will change even though policy options remain under review",
      "Remove concerned employees from testing because their feedback may be biased",
    ],
    correct: 1,
    explanation: "Timely communication can distinguish facts from uncertainty and show how employees can engage, which reduces the vacuum feeding rumors. Silence allows speculation to harden, unsupported denial risks trust, and excluding concerned users removes valuable feedback and reinforces suspicion.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Communication",
    domain: "People",
    topic: "Communication",
    approach: "Predictive",
    difficulty: "Easy",
    decisionRule: "confirm that an urgent verbal agreement is captured and understood by all responsible parties.",
    text: "During a site walk, the client verbally approves relocating a drainage inlet and the contractor plans to act that afternoon. Several affected designers were absent. What should the project manager do next?",
    choices: [
      "Let the contractor proceed because verbal communication is faster than project documentation",
      "Wait for the next monthly meeting and then ask whether anyone objects",
      "Document the agreement, verify authority and impacts, and distribute it through the agreed channel",
      "Ask the contractor to decide whether the absent designers need to know",
    ],
    correct: 2,
    explanation: "A prompt record, authority check, impact review, and distribution prevent an informal exchange from becoming uncontrolled work. Immediate action may bypass change controls, a monthly wait is too slow for the planned work, and the contractor should not determine communication needs for affected design owners.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "coach through questions that help the learner own the next experiment.",
    text: "A new iteration manager asks the agile coach to provide the exact words for addressing a team that chronically overcommits. The manager understands the metrics but lacks confidence. What should the coach do?",
    choices: [
      "Take over the next retrospective and demonstrate expert facilitation without involving the manager",
      "Provide a mandatory script and require the manager to follow it word for word",
      "Escalate the overcommitment because a trained iteration manager should already solve it",
      "Ask the manager to diagnose the pattern, rehearse options, and choose a facilitation experiment",
    ],
    correct: 3,
    explanation: "Guided diagnosis, rehearsal, and a learner-owned experiment build judgment and confidence for future situations. Taking over creates dependence, a rigid script suppresses adaptation, and escalation treats a development need as failure rather than using the manager's existing knowledge as a foundation.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Hybrid",
    difficulty: "Hard",
    decisionRule: "give specific, timely feedback on observable behavior and jointly plan practice.",
    text: "A technically strong workstream lead dominates planning, answers questions directed to others, and later complains that team members show no initiative. The lead asks for promotion advice. How should the project manager respond?",
    choices: [
      "Describe the observed behaviors and impacts, seek the lead's view, and agree on delegated facilitation practices",
      "Recommend a trial deputy-lead assignment with team feedback before the promotion decision",
      "Rotate planning facilitation among team members while the workstream lead observes",
      "Share the leadership competency model and ask the lead for a self-assessment",
    ],
    correct: 0,
    explanation: "Concrete behavior-impact feedback paired with dialogue and practice gives the lead an actionable development path. A trial assignment tests promotion readiness before addressing the observed cause, rotating facilitators changes the meeting but gives the lead no direct feedback, and a competency self-assessment is useful reflection yet may not connect the specific conduct to declining initiative.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Predictive",
    difficulty: "Medium",
    decisionRule: "use mentoring to transfer contextual judgment, not to make the mentee's decisions.",
    text: "A junior project manager preparing a first vendor negotiation asks a senior mentor which concession to offer. Several commercial options are acceptable within authority limits. What should the mentor do?",
    choices: [
      "Select the concession because the mentor has more negotiation experience",
      "Share relevant experience, explore criteria and consequences, and let the junior manager decide",
      "Attend the negotiation and answer every vendor question on the junior manager's behalf",
      "Decline to discuss the negotiation because mentoring must remain purely informal",
    ],
    correct: 1,
    explanation: "The mentor should transfer experience and decision reasoning while preserving the mentee's accountability within approved limits. Choosing the concession or taking over the meeting prevents capability growth, while refusing relevant guidance misunderstands mentoring and wastes a legitimate learning opportunity.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Agile",
    difficulty: "Hard",
    decisionRule: "address a repeated skill gap with evidence, support, and explicit improvement expectations.",
    text: "A tester misses subtle accessibility defects despite prior informal tips. Pairing records show progress on basic checks but recurring gaps on keyboard navigation. The release has sufficient time for focused development. What should the team leader do?",
    choices: [
      "Assign current accessibility review to a senior tester and schedule development after release",
      "Extend pairing on live stories and rely on peer feedback when keyboard defects appear",
      "Agree on focused coaching, practice cases, review checkpoints, and a measurable improvement expectation",
      "Enroll the tester in a general accessibility course and reassess after the next release",
    ],
    correct: 2,
    explanation: "A specific, supported improvement plan matches the demonstrated keyboard-navigation gap and makes progress observable within the available time. Senior review protects the release but postpones development, informal pairing lacks focused cases and checkpoints, and a general course is less targeted and defers evidence of improvement until after another release.",
    chapterId: "pmbok-ch09-resource-management",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Hybrid",
    difficulty: "Easy",
    decisionRule: "create a deliberate knowledge-transfer relationship before a critical transition.",
    text: "A veteran commissioning manager will retire before the final two plants start up, and a capable deputy has never led emergency handover decisions. What should the project manager do?",
    choices: [
      "Wait until the retirement date because the deputy already meets the formal job description",
      "Ask the veteran to write a general lessons-learned memo during the final week",
      "Hire an external manager to avoid placing development demands on the deputy",
      "Establish mentoring through shadowed decisions, simulations, and progressively delegated authority",
    ],
    correct: 3,
    explanation: "Progressive, experiential mentoring transfers tacit judgment and lets the deputy demonstrate readiness before the transition. Waiting accepts avoidable continuity risk, a final memo cannot capture decision practice, and external hiring bypasses a capable successor without first developing the identified gap.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "help the team discover its own answer when it has the knowledge and authority.",
    text: "A mature data team asks the project manager to settle how many experiments it should run concurrently. Flow data and customer priorities are visible to the team. What should the project manager do?",
    choices: [
      "Coach the team to interpret the data, select a limit, and inspect the result",
      "Set the concurrency limit alone because resource decisions belong to management",
      "Ask the sponsor to prescribe a limit that will maximize visible activity",
      "Allow unlimited experiments because mature teams do not need operating constraints",
    ],
    correct: 0,
    explanation: "The team possesses both evidence and authority, so coaching it to choose and inspect a limit strengthens its decision capability. A manager-imposed limit is unnecessary, sponsor prescription is remote from the work, and unlimited concurrency ignores the flow problem the team is trying to solve.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "agree on coaching boundaries so development support does not replace formal accountability.",
    text: "A functional manager asks the project manager to coach an analyst on stakeholder presentations, then asks for confidential details of every coaching conversation for the annual appraisal. What should the project manager do?",
    choices: [
      "Provide full conversation notes because the functional manager owns the appraisal",
      "Agree upfront on development goals and progress reporting while protecting personal coaching dialogue",
      "Refuse all coaching because line management and projects must never share development goals",
      "Coach the analyst secretly and tell the manager only after the appraisal is complete",
    ],
    correct: 1,
    explanation: "Clear boundaries can support legitimate progress reporting without turning a developmental relationship into covert performance surveillance. Full notes inhibit candor, refusing collaboration wastes aligned support, and secret coaching damages transparency with both the analyst and functional manager.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Coaching and mentoring",
    domain: "People",
    topic: "Coaching and mentoring",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "adapt coaching to evidence of mastery and withdraw support progressively.",
    text: "After three releases, a product analyst independently facilitates discovery sessions and handles difficult stakeholder questions well. The assigned mentor still attends every session and answers first. What should happen next?",
    choices: [
      "Continue the arrangement because expert presence can only improve stakeholder confidence",
      "Replace the analyst's development goal with more observation of the mentor",
      "Review readiness with the analyst and mentor, then reduce support while retaining periodic feedback",
      "End the mentoring relationship immediately without discussing future development needs",
    ],
    correct: 2,
    explanation: "Evidence shows growing mastery, so a jointly planned reduction in support preserves autonomy while maintaining useful feedback. Constant expert intervention now limits ownership, more observation ignores demonstrated skill, and abrupt termination misses a healthy transition and any next development goals.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "design time-zone practices with the team and distribute inconvenience fairly.",
    text: "A global engineering team schedules every live coordination meeting for headquarters morning, requiring the Asia-based specialists to attend late at night. Attendance remains high, but their participation and response quality are falling. What should the project manager do?",
    choices: [
      "Keep the schedule because headquarters includes the largest number of participants",
      "Replace live meetings with headquarters recordings and remove all real-time interaction",
      "Ask the Asia specialists to submit more detailed notes before each late meeting",
      "Co-design rotating meeting times and asynchronous handoffs while preserving essential overlap",
    ],
    correct: 3,
    explanation: "Rotating inconvenience and strengthening asynchronous handoffs support inclusion without losing necessary real-time collaboration. Majority convenience alone externalizes fatigue, recordings eliminate useful exchange, and more preparation from the disadvantaged group adds burden without correcting the inequitable schedule.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "make differing communication norms explicit before interpreting silence as agreement.",
    text: "In virtual retrospectives, team members from one regional office rarely challenge proposals in the group call but send substantial concerns afterward. The facilitator assumes they are disengaged. What should the facilitator do?",
    choices: [
      "Discuss participation preferences and add structured silent input and round-robin review",
      "Require every person to debate spontaneously or record nonparticipation in performance feedback",
      "Ignore later concerns because only statements made during the retrospective are valid",
      "Assign the regional office a separate retrospective with no cross-team discussion",
    ],
    correct: 0,
    explanation: "Structured written and round-robin participation accommodates different norms while keeping the whole team in one learning process. Forced spontaneous debate confuses style with commitment, rejecting later input loses evidence, and permanently separate retrospectives reduce shared understanding and integration.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "build trust through visible commitments and reliable follow-through, not surveillance.",
    text: "A remotely formed research consortium has never worked together. Members repeatedly ask whether partners are progressing and propose mandatory webcam monitoring throughout the workday. What should the project manager recommend?",
    choices: [
      "Adopt continuous monitoring because new virtual teams need proof of individual effort",
      "Create transparent team commitments, short coordination cadences, and visible completed outcomes",
      "Let each institution report only to its own manager to preserve local trust",
      "Delay collaborative work until an in-person meeting can be funded",
    ],
    correct: 1,
    explanation: "Trust grows when members make clear commitments, expose relevant progress, and reliably deliver outcomes. Continuous monitoring measures presence and signals distrust, institution-only reporting preserves silos, and postponing work treats physical colocation as a prerequisite despite available collaborative practices.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "confirm shared meaning when language fluency and specialist vocabulary intersect.",
    text: "A multilingual software team agrees in a video call to freeze an interface, but two members later implement changes because they understood freeze to mean discourage rather than prohibit. What should the scrum master do?",
    choices: [
      "Require only native speakers to participate in future interface decisions",
      "Ask the two members to reverse their work without discussing the misunderstanding",
      "Define key terms visually, use examples, and have participants confirm the decision in their own words",
      "Move all technical decisions to email because written language is always unambiguous",
    ],
    correct: 2,
    explanation: "Visual definitions, examples, and confirmation reveal differences in meaning before work proceeds. Excluding non-native speakers wastes expertise, silent reversal leaves the cause intact, and email can preserve the same ambiguous term without the feedback needed to test comprehension.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "address remote relationship strain directly with evidence and a shared collaboration reset.",
    text: "Two country teams exchange technically correct handoff documents but increasingly describe each other as careless in private chats. Minor clarifications now wait until formal weekly meetings. What should the project manager do next?",
    choices: [
      "Increase document templates because interpersonal concerns disappear when forms are complete",
      "Route all handoffs through the project manager to prevent direct friction",
      "Move one country's work to a supplier so the teams no longer depend on each other",
      "Facilitate a joint review of recent handoffs, impacts, assumptions, and quicker contact agreements",
    ],
    correct: 3,
    explanation: "A joint evidence-based reset addresses deteriorating trust and establishes faster interaction around the real handoffs. More forms do not repair attribution, routing everything through the project manager creates a bottleneck, and removing dependency through outsourcing is disproportionate and avoids the collaboration issue.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "onboard remote members through relationships, context, and early supported contribution.",
    text: "A developer joins a mature virtual team and receives repository access and recorded meetings, but contributes little and asks basic questions privately after two sprints. What should the team leader do?",
    choices: [
      "Pair the developer with rotating teammates, explain team context, and select a supported starter outcome",
      "Send additional recordings and wait another two sprints before involving teammates",
      "Assign an independent complex feature so the developer must learn the system quickly",
      "Reduce the developer's meeting access until technical knowledge reaches the team's level",
    ],
    correct: 0,
    explanation: "Remote onboarding requires social connections, contextual knowledge, and a safe path to meaningful contribution, which pairing and a bounded outcome provide. More passive material does not build relationships, a complex solo assignment raises failure risk, and reduced access further isolates the new member.",
    chapterId: "pmbok-ch10-communications-management",
  },
  {
    tag: "Virtual and cross-cultural collaboration",
    domain: "People",
    topic: "Virtual and cross-cultural collaboration",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "integrate cultural and local-calendar knowledge into one transparent delivery plan.",
    text: "Regional teams independently planned user training, overlooking that one country's launch overlaps a major holiday and another requires local-language accreditation. The integrated milestone is now at risk. What should the project manager do?",
    choices: [
      "Hold every region to the original dates because local constraints should have been raised earlier",
      "Bring regional leads together to revise dependencies, ownership, and locally valid readiness criteria",
      "Cancel localization so all regions can use the headquarters training package",
      "Let each region choose a launch date without updating the integrated program plan",
    ],
    correct: 1,
    explanation: "Joint replanning incorporates legitimate regional constraints into one controlled delivery picture and clarifies who owns readiness. Enforcing infeasible dates ignores known facts, canceling localization may invalidate adoption or accreditation, and uncoordinated regional dates hide cross-program dependencies rather than integrating them.",
    chapterId: "pmbok-ch04-integration-management",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "negotiate from shared value and constraints rather than positional feature counts.",
    text: "A product owner and operations manager disagree over whether the next sprint should add customer features or automate a fragile deployment step. Both have credible evidence. What should the project manager facilitate?",
    choices: [
      "Divide sprint capacity equally without examining the relative outcomes",
      "Let the product owner decide because the backlog is exclusively a product concern",
      "Compare customer value, operational risk, and timing, then agree on the best combined option",
      "Ask developers to work overtime so neither party needs to make a tradeoff",
    ],
    correct: 2,
    explanation: "An interests-and-evidence discussion can reveal sequencing or a combined outcome that protects both value and reliability. Equal capacity may be arbitrary, product ownership does not erase operational risk, and overtime avoids prioritization while transferring the conflict's cost to the team.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "use explicit decision criteria when expert opinions remain divided after exploration.",
    text: "Three architects evaluate two cloud designs and remain evenly divided after prototypes. One design costs less; the other recovers faster and has stronger regulatory evidence. A decision is due today. What should the project manager do?",
    choices: [
      "Delay the decision until all architects voluntarily reach unanimous agreement",
      "Select the least expensive design because cost is the only objective measure",
      "Take an unrecorded vote and omit dissent to present a unified team",
      "Apply agreed weighted criteria and decision authority, documenting tradeoffs and dissent",
    ],
    correct: 3,
    explanation: "When exploration does not create consensus, transparent criteria and established authority support a timely, traceable decision. Waiting for unanimity may be impossible, cost alone ignores recovery and compliance, and an unrecorded vote conceals decision rationale and relevant dissent.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "clarify the decision rule before inviting participation so consultation is not mistaken for consensus.",
    text: "A team workshop gathers options for changing its support model. After discussion, several members insist that any decision requires unanimity, although the service owner remains accountable for operational coverage. What should the facilitator do?",
    choices: [
      "Continue discussion until every participant supports one option regardless of urgency",
      "Clarify the service owner's decision authority, consultation criteria, and how concerns will be addressed",
      "Let the loudest team members decide because they show the strongest commitment",
      "Cancel the workshop and have the sponsor design the support model alone",
    ],
    correct: 1,
    explanation: "Participants need to know how input informs the accountable decision and how legitimate concerns will be handled. Unanimity was not established and may stall action, volume is not authority, and sponsor takeover discards the service owner's accountability and the team's useful operating knowledge.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "maintain ethical and governance boundaries while seeking alternative negotiating value.",
    text: "A licensing partner offers a critical discount if the project manager privately shares a competitor's confidential bid range. Budget pressure is severe, and the partner says no record is necessary. What should the project manager do?",
    choices: [
      "Share only an approximate range because the discount benefits the project",
      "Ask a team member without procurement authority to provide the information instead",
      "End all negotiation and blacklist the licensing partner without documenting the request",
      "Refuse the request, document it appropriately, and negotiate using authorized commercial information",
    ],
    correct: 3,
    explanation: "Confidentiality and procurement integrity are nonnegotiable boundaries, while legitimate pricing and value terms remain available for discussion. An approximate range still discloses protected information, using an intermediary remains unethical, and undocumented immediate blacklisting bypasses proportionate organizational review.",
    chapterId: "pmbok-ch03-project-manager-role",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Agile",
    difficulty: "Medium",
    decisionRule: "build a decision coalition by connecting stakeholder interests to a shared outcome.",
    text: "A city-services app needs one identity standard, but transit, libraries, and recreation departments favor their existing systems. None can impose a decision on the others. What should the project manager do?",
    choices: [
      "Allow three identity systems because avoiding negotiation preserves departmental relationships",
      "Ask the software vendor to choose whichever integration is easiest to build",
      "Facilitate shared citizen outcomes, constraints, and evidence to negotiate a cross-department standard",
      "Escalate each department separately until one executive agrees to overrule the others",
    ],
    correct: 2,
    explanation: "A coalition based on citizen outcomes and transparent constraints can create commitment to a shared standard without unilateral authority. Three systems preserve fragmentation, vendor convenience is not public value, and fragmented escalation encourages political positioning instead of a joint decision.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
  {
    tag: "Negotiation and decision making",
    domain: "People",
    topic: "Negotiation and decision making",
    approach: "Hybrid",
    difficulty: "Medium",
    decisionRule: "reopen negotiation when new stakeholder evidence changes the assumptions supporting an agreement.",
    text: "A hospital and software supplier agreed to train super-users after configuration ends. Pilot nurses now show that late training will miss workflow defects, while the supplier says earlier involvement requires scarce specialists. What should the project manager do next?",
    choices: [
      "Enforce the original agreement because reopening it would weaken negotiating credibility",
      "Require the nurses to document defects after launch so the supplier schedule remains intact",
      "Move all configuration decisions to the supplier because its specialists are scarce",
      "Share the pilot evidence and negotiate targeted early sessions, priorities, and resource tradeoffs",
    ],
    correct: 3,
    explanation: "The pilot provides material new evidence, so a focused renegotiation can target the workflows where early specialist access has the most value. Rigid enforcement ignores changed assumptions, post-launch discovery raises adoption risk, and supplier-only decisions exclude the clinicians who understand operational fit.",
    chapterId: "pmbok-ch13-stakeholder-management",
  },
];
